name: Build with guix (manual trigger)

on: workflow_dispatch

jobs:
  build:
    name: "build"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install required packages
        run: |
          sudo apt-get install guix
          sudo apt-get install cmake
      - name: Cache guix
        uses: actions/cache@v4
        with:
            path: |
              ~/.cache/guix
              /gnu/store
            key: guix-cache-
            restore-keys: |
              guix-cache-
      - name: Download macOS Xcode
        run: |
          mkdir depends/SDKs
          wget https://bitcoincore.org/depends-sources/sdks/Xcode-12.2-12B45b-extracted-SDK-with-libcxx-headers.tar.gz
          tar -xaf Xcode-12.2-12B45b-extracted-SDK-with-libcxx-headers.tar.gz -C depends/SDKs/
      - name: Build with guix
        run: |
          HOSTS=x86_64-linux-gnu ./contrib/guix/guix-build